travis:
  secure:
    BINSTAR_TOKEN: O9Q2RlHBgFjFtzIguyIpC9uPyC4jx7x7Mz68vung8eANN82Enx08B3Xe7IEeYCDIb6pQHs7t/MZyQzzuk6P+QCVh54SsXUruv0NpC6g0irsolBTPE/WfzuvaxOkvGKjmJufQMd6xg7SXH+XAH5ecwPogrn+7X1zqZegj4wGmXyh1u7e/bUpUQ+8Ad+lyz4isBm+SI0WkulHCMtlhOf6eKUC3zMZBD+d2xM4sXXLg6h0NOILrMb5dcvmIxni0Q9GJGYEr7MFeXliNxkTRKjZH9LkI9lof5EKvxNQgux8iDz1jNWzyYYmDrV2CexBUzjstTwSLFafL9jKHK/tnYDBFMkvt1ziDsb2y7AY0AycgeTDuk5arFB2GRYKA9riW5Cw/0MnXC5wVJwYQ34IT6iDDO613cpF1vBU2fFVVVUU9r4iDM/4dCP4rVd9grRF8obLRMrEEv0UM3FuAsmiyDCnBaGziw8ZxDD6FJdB+wo0RU2XnU0NTq1/5R1Xna7FDUstilPwRXVq5efwWzpypHcIOHoHVlIcPHNRg+U+i99rq4Bv1e8nN73ySvFrp9LlCjY5CJ30HJ0AjbnFinSH0924eL2uTmoA4pcpwPlQD/c/M27vX/YkSWz66POcEeoSTYTZuj+ikzuELn/re+SzP85A4FTIX6VZlm/Mhl5KuD1qvfow=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
