travis:
  secure:
    BINSTAR_TOKEN: QgmV4gecsebbb/s127vFY2OktGqoO6nmgNvcBSzV/vL1JhoBgHcYfQiNirILyyjzHMf4ssV2epqg+Z9Oo/BVMcOdRe2Hspfi+3pvQriHSY5seDCsRZ3cp4ydUyKPtA2k5a7gk2fp1xCBJzo2gkZFA5pnv7jyAr4rm3Jff/al6PSj7s3K9jtsoM8PsheQedTCe0VQqUgiKiEM3s5UUIDcC1ZDnRZkIi9J/5P7sBtgn5pUmGloyfT9kGH8ZNpSRkcHMthMpTIv2S6f38RuyU1vSQ5OfEIFG8Ym4MEprik2N77zQIWJY6EM4fX9ZlqCoMLO0GFusQT7/iUOCFEUAZzzLtkms4Bno0/aoNxwr9ZV0GfXlV+Ri7SB4jxPASrAW+XgfdMX896jckhFySlfy1Ze2JbkkzX0fXOpble2M40UKEPP2E3jX4FzueQzmOaYF4cL8swxZymBfrvVW1gmTxu2dXpPyEnf5YtJvM6otuBX0rQvEqIBVbOkvuzjQp0tpNLPcLFf8YsQXd7k9zOKvx/4ylKUVYNCrj6A1AMTTWpjL4vPIPk4nLN1tl8ehnzf6RQkcZi7gwk0z/8EdqM8aIiruXJvVvy/Op454wl9eScOcQ3wTe+0UI4t5Sx9S8lirhnezeAwgQk1SrFE3SPwriCAeM+WBNn84cnRE6qA8xJwCAw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
